language: python
python:
  - "2.7"
# command to install dependencies
install:
  - "pip install ."
# run before the main script
before_script:
  - "git --version"
# command to run tests
script: nosetests --logging-level=DEBUG
# The following line tells Travis CI to build in a container
sudo: false
